#!/usr/bin/env bash
# install-systemd.sh — set up the trd user systemd service.
#
# Runs entirely as your current shell user. NEVER invokes sudo. NEVER
# touches anything outside $HOME. The dispatcher will run as the same
# user that runs this script — verify with `whoami` first if unsure.
#
# After this script:
#   • The unit lives at $HOME/.config/systemd/user/trd.service
#   • systemd --user supervises it (crashes/OOMs respawn in ~2s)
#   • `make restart` switches to `systemctl --user restart trd`
#   • Live logs: `journalctl --user -u trd -f`
#
# One thing you may want to do once, manually:
#
#   sudo loginctl enable-linger "$USER"
#
# Without it, systemd kills your --user services when you log out
# (fine for an interactive workstation, fatal for a headless host
# you ssh in and out of). This script prints the command and the
# current state at the end so you can decide; it does not run sudo
# itself.

set -euo pipefail

if [ "$(id -u)" -eq 0 ]; then
	echo "error: do NOT run as root — trd is a --user service." >&2
	echo "       (re-run as the unprivileged user that should own the dispatcher;" >&2
	echo "        the unit is installed under that user's \$HOME and runs as them.)" >&2
	exit 2
fi

if ! command -v systemctl >/dev/null 2>&1; then
	echo "error: systemctl not found. This host doesn't appear to use systemd." >&2
	echo "       Use the tmux-based 'make start' fallback instead." >&2
	exit 1
fi

BIN="${HOME}/.local/bin/trd"
if [ ! -x "${BIN}" ]; then
	echo "error: ${BIN} is missing or not executable." >&2
	echo "       Run 'make install' first." >&2
	exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_UNIT="${SCRIPT_DIR}/trd.service"
if [ ! -f "${SRC_UNIT}" ]; then
	echo "error: ${SRC_UNIT} not found." >&2
	exit 1
fi

UNIT_DIR="${HOME}/.config/systemd/user"
mkdir -p "${UNIT_DIR}"

DST_UNIT="${UNIT_DIR}/trd.service"
install -m 0644 "${SRC_UNIT}" "${DST_UNIT}"

# systemd --user starts with an almost empty environment — no PATH, no
# nvm shims, no $HOME-local bin dirs. trd spawns `omp` (and omp itself
# shells out to node/git/etc.), so we drop an env.conf override that
# captures the *current login shell's* PATH plus an absolute pin to
# whatever `omp` resolves to right now. Re-run install-systemd whenever
# you switch node versions (nvm) so the pin tracks.
DROPIN_DIR="${UNIT_DIR}/trd.service.d"
mkdir -p "${DROPIN_DIR}"
DROPIN="${DROPIN_DIR}/env.conf"

OMP_BIN="$(command -v omp || true)"
if [ -z "${OMP_BIN}" ]; then
	echo "warning: 'omp' not found on PATH at install time." >&2
	echo "         trd will still start but agent spawns will fail until" >&2
	echo "         either (a) omp is installed and install-systemd is re-run," >&2
	echo "         or (b) TRD_OMP_BIN is set in ${DROPIN}." >&2
fi

{
	echo "# Generated by scripts/install-systemd.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "# Re-run 'make install-systemd' to regenerate."
	echo "[Service]"
	echo "Environment=PATH=${PATH}"
	if [ -n "${OMP_BIN}" ]; then
		echo "Environment=TRD_OMP_BIN=${OMP_BIN}"
	fi
} > "${DROPIN}"
chmod 0644 "${DROPIN}"

echo "installing trd user service"
echo "  user:    ${USER}  (uid $(id -u))"
echo "  binary:  ${BIN}"
echo "  unit:    ${DST_UNIT}"
echo "  env:     ${DROPIN}"
if [ -n "${OMP_BIN}" ]; then
	echo "  omp:     ${OMP_BIN}"
fi
echo

systemctl --user daemon-reload
systemctl --user enable --now trd.service

echo
echo "trd is running under systemd --user as ${USER}."
echo "  systemctl --user status trd        # service status"
echo "  journalctl --user -u trd -f         # live logs"
echo "  systemctl --user restart trd       # bounce after rebuild"
echo

# Lingering check — informational only. We never run sudo from here.
linger_state="unknown"
if command -v loginctl >/dev/null 2>&1; then
	if loginctl show-user "${USER}" 2>/dev/null | grep -q '^Linger=yes$'; then
		linger_state="enabled"
	else
		linger_state="disabled"
	fi
fi

case "${linger_state}" in
enabled)
	echo "lingering: enabled — trd will keep running after you log out. Nothing more to do."
	;;
disabled)
	echo "lingering: disabled — trd will stop when you log out of all sessions."
	echo "  To keep it running on a headless host, run this ONCE (requires sudo):"
	echo "    sudo loginctl enable-linger \"\$USER\""
	;;
*)
	echo "lingering: could not detect (loginctl unavailable). On a headless host"
	echo "  you typically want: sudo loginctl enable-linger \"\$USER\""
	;;
esac

echo
echo "If a previous tmux session 'trd' is still running, kill it now:"
echo "  tmux kill-session -t trd"
